title: MASTERHU
email: masterhu663@gmail.com
url: "https://masterhu663.github.io"
baseurl: "/robotics.github.io"
highlighter: rouge

# Navigation links
navigation:
  - title: // HOME
    url: /
  - title: // PROJECTS
    url: /projects/
  - title: // CONTACT
    url: /contact/

  