markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # 或 "air", "sunrise" 等

plugins:
  - jekyll-include-cache

title: MASTERHU
email: your-real-email@example.com
description: ''
url: "https://masterhu663.github.io"
baseurl: "/robotics.github.io"

collections:
  robot_learning:
    output: true
    permalink: /robot-learning/:path/

defaults:
  - scope:
      path: ""
      type: "robot_learning"
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "robot_learning_nav"
      toc: true
      toc_sticky: true

      